CREATE DATABASE QLBQA

CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(10) PRIMARY KEY,
	TENNCC NVARCHAR(50),
	SDTNCC VARCHAR(10),
	DIACHINCC NVARCHAR(100),
)

CREATE TABLE NHOMQUYEN
(
	MAQUYEN VARCHAR(10) PRIMARY KEY,
	TENQUYEN NVARCHAR(50),
	MOTAQUYEN NVARCHAR(200),
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	NV_MAQUYEN VARCHAR(10),
	TENNV NVARCHAR(50),
	TUOI INT CHECK(TUOI>=18 AND TUOI<=30),
	GT NVARCHAR(3) CHECK(GT IN(N'Nam', N'Nữ')),
	SDTNV VARCHAR(10),
	DIACHINV NVARCHAR(100),
	CONSTRAINT NV_MAQUYEN_FK FOREIGN KEY (NV_MAQUYEN) REFERENCES NHOMQUYEN(MAQUYEN),
)

CREATE TABLE PHIEUNHAP
(
	MAPN VARCHAR(10) PRIMARY KEY,
	PN_MANCC VARCHAR(10),
	PN_MANV VARCHAR(10),
	NGAYNHAP DATE,
	PN_TONGTIEN FLOAT,
	CONSTRAINT PN_MANCC_FK FOREIGN KEY (PN_MANCC) REFERENCES NHACUNGCAP(MANCC),
	CONSTRAINT PN_MANV_FK FOREIGN KEY (PN_MANV) REFERENCES NHANVIEN(MANV),
)


CREATE TABLE THUONGHIEU
(
   MATH VARCHAR(10) PRIMARY KEY,
   TENTH NVARCHAR(50)
)

CREATE TABLE SANPHAM
(
	MASP VARCHAR(10) PRIMARY KEY,
	SP_MATH VARCHAR(10),
	TENSP NVARCHAR(50),
	SIZE VARCHAR(3),
	MAUSAC NVARCHAR(10),
	SP_GIASP FLOAT,
	SP_SOLUONGSP INT,
	TRANGTHAI NVARCHAR(3) CHECK(TRANGTHAI IN (N'Còn', N'Hết')),
	CONSTRAINT MATH_FK FOREIGN KEY (SP_MATH) REFERENCES THUONGHIEU(MATH)
)

CREATE TABLE KICHCO
(
   MASIZE VARCHAR(10) PRIMARY KEY,
   TENSIZE VARCHAR(3)
)

CREATE TABLE MAUSAC
(
   MAMAU VARCHAR(10) PRIMARY KEY,
   TENMAU NVARCHAR(10)
)

CREATE TABLE KHUYENMAI
(
   MAKM VARCHAR(10) PRIMARY KEY,
   TENKM NVARCHAR(50),
   DIEUKIEN VARCHAR(50),
   NGAY_BD DATE,
   NGAY_KT DATE,
   GIAMGIA FLOAT
)

CREATE TABLE CHITIETSANPHAM
(
   MASP VARCHAR(10),
   MASIZE VARCHAR(10),
   MAMAU VARCHAR(10),
   CONSTRAINT CTSP_PK PRIMARY KEY (MASP,MASIZE,MAMAU),
   CONSTRAINT MASP_FK FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
   CONSTRAINT MASIZE_FK FOREIGN KEY (MASIZE) REFERENCES KICHCO(MASIZE),
   CONSTRAINT MAMAU_FK FOREIGN KEY (MAMAU) REFERENCES MAUSAC(MAMAU)
)

CREATE TABLE CHITIETPHIEUNHAP
(
	CTPN_MAPN VARCHAR(10),
	CTPN_MASP VARCHAR(10),
	CTSP_GIASP FLOAT,
	CTSP_SOLUONGSP INT,
	CONSTRAINT CTPN_MAPN_FK FOREIGN KEY (CTPN_MAPN) REFERENCES PHIEUNHAP(MAPN),
	CONSTRAINT CTPN_MASP_FK FOREIGN KEY (CTPN_MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT CTPN_PK PRIMARY KEY (CTPN_MASP, CTPN_MAPN),
)

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50),
	SDTKH VARCHAR(10),
	DIACHIKH NVARCHAR(100),
)

	CREATE TABLE HOADON
(
	MAHD VARCHAR(10) PRIMARY KEY,
	HD_MAKH VARCHAR(10),
	HD_MANV VARCHAR(10),
	NGAYNHAP DATE,
	HD_TONGTIEN FLOAT,
	CONSTRAINT HD_MAKH_FK FOREIGN KEY (HD_MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT HD_MANV_FK FOREIGN KEY (HD_MANV) REFERENCES NHANVIEN(MANV),
)

CREATE TABLE CHITIETHOADON
(CTHD_MAHD VARCHAR(10),
	CTHD_MASP VARCHAR(10),
	DONGIA FLOAT,
	CTHD_SOLUONG INT,
	CONSTRAINT CTHD_MAHD_FK FOREIGN KEY (CTHD_MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT CTHD_MASP_FK FOREIGN KEY (CTHD_MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT CTHD_PK PRIMARY KEY (CTHD_MAHD, CTHD_MASP),
)

CREATE TABLE CHUCNANG
(
	TENCN NVARCHAR(30) PRIMARY KEY,
	MOTA NVARCHAR(200),
)

CREATE TABLE CHITIETPHANQUYEN
(
	CTPQ_MAQUYEN VARCHAR(10),
	CTPQ_TENCN NVARCHAR(30),
	CONSTRAINT CTPQ_MAQUYEN_FK FOREIGN KEY (CTPQ_MAQUYEN) REFERENCES NHOMQUYEN(MAQUYEN),
	CONSTRAINT CTPQ_TENCN_FK FOREIGN KEY (CTPQ_TENCN) REFERENCES CHUCNANG(TENCN),
	CONSTRAINT CTPQ_PK PRIMARY KEY (CTPQ_MAQUYEN, CTPQ_TENCN),
)

CREATE TABLE TAIKHOAN
(
	Username varchar(10) primary key,
	matKhau varchar(10),
	MaQuyen varchar(10),
	CONSTRAINT Username_FK FOREIGN KEY (Username) REFERENCES NHANVIEN(MANV)
)






