CREATE DATABASE QUANLY_BQA
USE QUANLY_BQA

CREATE TABLE [NHACUNGCAP] (
  [MANCC] VARCHAR(10) PRIMARY KEY,
  [TENNCC] NVARCHAR(50),
  [SDTNCC] VARCHAR(10),
  [DIACHINCC] NVARCHAR(100),
  [TRANGTHAI] NVARCHAR(50)
)
GO

CREATE TABLE [NHOMQUYEN] (
  [MAQUYEN] VARCHAR(10) PRIMARY KEY,
  [TENQUYEN] NVARCHAR(50),
  [MOTAQUYEN] NVARCHAR(200),
  [TRANGTHAI] NVARCHAR(50)
)
GO

CREATE TABLE [NHANVIEN] (
  [MANV] VARCHAR(10) PRIMARY KEY,
  [TENNV] NVARCHAR(50),
  [NGAYSINH] DATE,
  [SDTNV] VARCHAR(10),
  [DIACHINV] NVARCHAR(100),
  [TRANGTHAI] NVARCHAR(50)
)
GO

CREATE TABLE [PHIEUNHAP] (
  [MAPN] VARCHAR(10) PRIMARY KEY,
  [PN_MANCC] VARCHAR(10),
  [PN_MANV] VARCHAR(10),
  [NGAYNHAP] DATE,
  [PN_TONGTIEN] FLOAT
)
GO

CREATE TABLE [THUONGHIEU] (
  [MATH] VARCHAR(10) PRIMARY KEY,
  [TENTH] NVARCHAR(50),
  [TRANGTHAI] NVARCHAR(30)
)
GO

CREATE TABLE [SANPHAM] (
  [MASP] VARCHAR(10) PRIMARY KEY,
  [SP_MATH] VARCHAR(10),
  [TENSP] NVARCHAR(50),
  [SIZE] VARCHAR(3),
  [MAUSAC] NVARCHAR(10),
  [HINHANH] VARCHAR(255),
  [SP_GIASP] FLOAT,
  [SP_SOLUONGSP] INT,
  [TRANGTHAI] NVARCHAR(10)
)
GO

CREATE TABLE [KICHCO] (
  [MASIZE] VARCHAR(10) PRIMARY KEY,
  [TENSIZE] VARCHAR(5)
)
GO

CREATE TABLE [MAUSAC] (
  [MAMAU] VARCHAR(10) PRIMARY KEY,
  [TENMAU] NVARCHAR(20)
)
GO

CREATE TABLE [KHUYENMAI] (
  [MAKM] VARCHAR(10) PRIMARY KEY,
  [TENKM] NVARCHAR(50),
  [DIEUKIEN] NVARCHAR(50),
  [GIAMGIA] FLOAT,
  [NGAY_BD] DATE,
  [NGAY_KT] DATE,
  [TRANGTHAI] NVARCHAR(50)
)
GO

CREATE TABLE [CHITIETSANPHAM] (
  [MASP] VARCHAR(10),
  [MASIZE] VARCHAR(10),
  [MAMAU] VARCHAR(10),
  PRIMARY KEY ([MASP], [MASIZE], [MAMAU])
)
GO

CREATE TABLE [CHITIETPHIEUNHAP] (
  [CTPN_MAPN] VARCHAR(10),
  [CTPN_MASP] VARCHAR(10),
  [CTSP_GIASP] FLOAT,
  [CTSP_SOLUONGSP] INT,
  PRIMARY KEY ([CTPN_MASP], [CTPN_MAPN])
)
GO

CREATE TABLE [KHACHHANG] (
  [MAKH] VARCHAR(10) PRIMARY KEY,
  [TENKH] NVARCHAR(50),
  [SDTKH] VARCHAR(10),
  [DIACHIKH] NVARCHAR(100),
  [TRANGTHAI] NVARCHAR(50)
)
GO

CREATE TABLE [HOADON] (
  [MAHD] VARCHAR(10) PRIMARY KEY,
  [HD_MAKH] VARCHAR(10),
  [HD_MAKM] VARCHAR(10),
  [HD_MANV] VARCHAR(10),
  [NGAYNHAP] DATE,
  [HD_TONGTIEN] FLOAT
)
GO

CREATE TABLE [CHITIETHOADON] (
  [CTHD_MAHD] VARCHAR(10),
  [CTHD_MASP] VARCHAR(10),
  [DONGIA] FLOAT,
  [CTHD_SOLUONG] INT,
  PRIMARY KEY ([CTHD_MAHD], [CTHD_MASP])
)
GO

CREATE TABLE [CHUCNANG] (
  [MACN] NVARCHAR(30) PRIMARY KEY,
  [TENCN] NVARCHAR(30),
  [MOTA] NVARCHAR(200)
)
GO

CREATE TABLE [CHITIETPHANQUYEN] (
  [CTPQ_MAQUYEN] VARCHAR(10),
  [CTPQ_MACN] NVARCHAR(30),
  PRIMARY KEY ([CTPQ_MAQUYEN], [CTPQ_MACN])
)
GO

CREATE TABLE [TAIKHOAN] (
  [Username] varchar(10) PRIMARY KEY,
  [matKhau] varchar(10),
  [MaQuyen] varchar(10),
  [TRANGTHAI] NVARCHAR(30)
)
GO

ALTER TABLE [HOADON] ADD CONSTRAINT [HD_MAKM_FK] FOREIGN KEY ([HD_MAKM]) REFERENCES [KHUYENMAI] ([MAKM])
GO

ALTER TABLE [TAIKHOAN] ADD CONSTRAINT [TK_MaQuyen_FK] FOREIGN KEY ([MaQuyen]) REFERENCES [NHOMQUYEN] ([MAQUYEN])
GO

ALTER TABLE [PHIEUNHAP] ADD CONSTRAINT [PN_MANCC_FK] FOREIGN KEY ([PN_MANCC]) REFERENCES [NHACUNGCAP] ([MANCC])
GO

ALTER TABLE [PHIEUNHAP] ADD CONSTRAINT [PN_MANV_FK] FOREIGN KEY ([PN_MANV]) REFERENCES [NHANVIEN] ([MANV])
GO

ALTER TABLE [SANPHAM] ADD CONSTRAINT [MATH_FK] FOREIGN KEY ([SP_MATH]) REFERENCES [THUONGHIEU] ([MATH])
GO

ALTER TABLE [CHITIETSANPHAM] ADD CONSTRAINT [MASP_FK] FOREIGN KEY ([MASP]) REFERENCES [SANPHAM] ([MASP])
GO

ALTER TABLE [CHITIETSANPHAM] ADD CONSTRAINT [MASIZE_FK] FOREIGN KEY ([MASIZE]) REFERENCES [KICHCO] ([MASIZE])
GO

ALTER TABLE [CHITIETSANPHAM] ADD CONSTRAINT [MAMAU_FK] FOREIGN KEY ([MAMAU]) REFERENCES [MAUSAC] ([MAMAU])
GO

ALTER TABLE [CHITIETPHIEUNHAP] ADD CONSTRAINT [CTPN_MAPN_FK] FOREIGN KEY ([CTPN_MAPN]) REFERENCES [PHIEUNHAP] ([MAPN])
GO

ALTER TABLE [CHITIETPHIEUNHAP] ADD CONSTRAINT [CTPN_MASP_FK] FOREIGN KEY ([CTPN_MASP]) REFERENCES [SANPHAM] ([MASP])
GO

ALTER TABLE [HOADON] ADD CONSTRAINT [HD_MAKH_FK] FOREIGN KEY ([HD_MAKH]) REFERENCES [KHACHHANG] ([MAKH])
GO

ALTER TABLE [HOADON] ADD CONSTRAINT [HD_MANV_FK] FOREIGN KEY ([HD_MANV]) REFERENCES [NHANVIEN] ([MANV])
GO

ALTER TABLE [CHITIETHOADON] ADD CONSTRAINT [CTHD_MAHD_FK] FOREIGN KEY ([CTHD_MAHD]) REFERENCES [HOADON] ([MAHD])
GO

ALTER TABLE [CHITIETHOADON] ADD CONSTRAINT [CTHD_MASP_FK] FOREIGN KEY ([CTHD_MASP]) REFERENCES [SANPHAM] ([MASP])
GO

ALTER TABLE [CHITIETPHANQUYEN] ADD CONSTRAINT [CTPQ_MAQUYEN_FK] FOREIGN KEY ([CTPQ_MAQUYEN]) REFERENCES [NHOMQUYEN] ([MAQUYEN])
GO

ALTER TABLE [CHITIETPHANQUYEN] ADD CONSTRAINT [CTPQ_TENCN_FK] FOREIGN KEY ([CTPQ_MACN]) REFERENCES [CHUCNANG] ([MACN])
GO

ALTER TABLE [TAIKHOAN] ADD CONSTRAINT [Username_FK] FOREIGN KEY ([Username]) REFERENCES [NHANVIEN] ([MANV])
GO
